// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmgn9ShotEvlovdBjMgRdDGh4M9G2uD_k',
    appId: '1:69898860936:web:532119086f8c28544e623d',
    messagingSenderId: '69898860936',
    projectId: 'firstproject-99744',
    authDomain: 'firstproject-99744.firebaseapp.com',
    storageBucket: 'firstproject-99744.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMgDVWfosKi09tU7_0EImyIhk-Mb6Gc4w',
    appId: '1:69898860936:android:8a652fbada319c484e623d',
    messagingSenderId: '69898860936',
    projectId: 'firstproject-99744',
    storageBucket: 'firstproject-99744.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR6QEtw0AjbpUp9fIo6pe_B_t8L049A0g',
    appId: '1:69898860936:ios:14d2c1e48407a2c84e623d',
    messagingSenderId: '69898860936',
    projectId: 'firstproject-99744',
    storageBucket: 'firstproject-99744.appspot.com',
    iosClientId: '69898860936-nh5pbt7i91f61tkqf1gv18vjvj1dghkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6QEtw0AjbpUp9fIo6pe_B_t8L049A0g',
    appId: '1:69898860936:ios:14d2c1e48407a2c84e623d',
    messagingSenderId: '69898860936',
    projectId: 'firstproject-99744',
    storageBucket: 'firstproject-99744.appspot.com',
    iosClientId: '69898860936-nh5pbt7i91f61tkqf1gv18vjvj1dghkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstAppFlutter',
  );
}
